node ('openstack-jenkins-slave') {
    try {
        def openshiftHeatBranch = 'v3.11'
        def openshiftDeploymentAnsibleBranch = 'v3.11'

        //slackSend color: 'good', message: "Pipeline build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"

        stage('code-checkout') {
            git branch:"$openshiftHeatBranch", url:"https://github.com/UKCloud/openshift-heat.git"
        }

        stage('setup OpenStack credentials') {
            sh "echo \"\" > openstack_rc.sh"
            sh "echo export OS_PASSWORD=`oc get secrets openstack --template='{{ .data.password }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export OS_USERNAME=`oc get secrets openstack --template='{{ .data.username }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo -e \"parameter_defaults:\\n  rhn_orgid: `oc get secrets rhelsubscriptions --template='{{ .data.rhel_org }}' | base64 --decode`\" | tee rhel_reg_creds.yaml"
            sh "echo -e \"  rhn_activationkey: `oc get secrets rhelsubscriptions --template='{{ .data.rhel_activation_key }}' | base64 --decode`\" | tee -a rhel_reg_creds.yaml"
            sh "echo -e \"  satellite_fqdn: `oc get secrets rhelsubscriptions --template='{{ .data.satellite_fqdn }}' | base64 --decode`\" | tee -a rhel_reg_creds.yaml"
            sh "echo -e \"  satellite_deploy: `oc get secrets rhelsubscriptions --template='{{ .data.satellite_deploy }}' | base64 --decode`\" | tee -a rhel_reg_creds.yaml"
            sh "echo export OS_PROJECT_ID=`oc get configmap openstack-config --template='{{ .data.openstack_project_id }}'` | tee -a openstack_rc.sh"
            sh "echo export OS_PROJECT_NAME=`oc get configmap openstack-config --template='{{ .data.openstack_project_name }}'` | tee -a openstack_rc.sh"
            sh "echo export OS_USER_DOMAIN_NAME=Default | tee -a openstack_rc.sh"
            sh "export OS_PROJECT_DOMAIN_ID=default | tee -a openstack_rc.sh"
            sh "echo export OS_AUTH_URL=`oc get configmap openstack-config --template='{{ .data.openstack_url }}'` | tee -a openstack_rc.sh"
            sh "echo export S3_ACCESS_KEY=`oc get secrets s3parameters --template='{{ .data.s3accesskey }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export S3_SECRET_KEY=`oc get secrets s3parameters --template='{{ .data.s3secretkey }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export S3_REGION_ENDPOINT=`oc get secrets s3parameters --template='{{ .data.s3regionendpoint }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export S3_BUCKET_NAME=`oc get secrets s3parameters --template='{{ .data.s3bucketname }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export OPENSHIFT_USERNAME=`oc get secrets openshift --template='{{ .data.username }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export OPENSHIFT_PASSWORD=`oc get secrets openshift --template='{{ .data.userpass }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export ADMIN_USERNAME=`oc get secrets openshift --template='{{ .data.adminuser }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export ADMIN_PASSWORD=`oc get secrets openshift --template='{{ .data.adminpass }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export DOMAIN_SUFFIX=`oc get secrets openshift --template='{{ .data.domainsuffix }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export LOCAL_DOMAIN_SUFFIX=`oc get secrets openshift --template='{{ .data.localdomainsuffix }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export CONTROL_PLANE_IP=`oc get secrets openshift --template='{{ .data.control_plane_ip }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export DATA_PLANE_IP=`oc get secrets openshift --template='{{ .data.data_plane_ip }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export WORKER_SMALL_SCALE=`oc get secrets openshift --template='{{ .data.worker_small_scale }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export WORKER_MEDIUM_SCALE=`oc get secrets openshift --template='{{ .data.worker_medium_scale }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export WORKER_LARGE_SCALE=`oc get secrets openshift --template='{{ .data.worker_large_scale }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export OCP_VERSION=`oc get secrets openshift --template='{{ .data.openshift_version }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export SET_NODE_ROUTES=`oc get secrets openshift --template='{{ .data.set_node_routes }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NODE_ROUTES=`oc get secrets openshift --template='{{ .data.node_routes }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export MULTINETWORK=`oc get secrets openshift --template='{{ .data.multinetwork }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_DNS_SERVER=`oc get secrets openshift --template='{{ .data.net2_dns_server }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_NETWORK=`oc get secrets openshift --template='{{ .data.net2_external_network }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_GATEWAY_IP=`oc get secrets openshift --template='{{ .data.net2_gateway_internal_ip }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_NTP_SERVER=`oc get secrets openshift --template='{{ .data.net2_ntp_servers }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_LARGE_NODE=`oc get secrets openshift --template='{{ .data.net2_worker_large_scale }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_MEDIUM_NODE=`oc get secrets openshift --template='{{ .data.net2_worker_medium_scale }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NET2_SMALL_NODE=`oc get secrets openshift --template='{{ .data.net2_worker_small_scale }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export SLACK_WEBHOOK=`oc get secrets openshift --template='{{ .data.slack_webhook_url_acme_sh }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export NEUSTAR_PASSWORD=`oc get secrets openshift --template='{{ .data.neustar_ultradns_password }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export DEPLOYEXTRAGATEWAY=`oc get secrets openshift --template='{{ .data.deploy_extra_gateway }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export REG_URL=`oc get secrets openshift --template='{{ .data.registry_url }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export REG_USER=`oc get secrets openshift --template='{{ .data.registry_user }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export REG_PASSWORD=`oc get secrets openshift --template='{{ .data.registry_password }}' | base64 --decode` | tee -a openstack_rc.sh"
            sh "echo export DEPLOY_KEY=`oc get secrets openshift --template='{{ .data.deploy_key }}' | base64 --decode` | tee -a openstack_rc.sh"
        }

        stage('cleanup HEAT environment') {
            sh 'source ./openstack_rc.sh ; openstack stack show openshift-\$OS_PROJECT_NAME && openstack stack delete openshift-\$OS_PROJECT_NAME --wait --yes || echo stack not found'
        }

        stage('setup host keys') {
            sh 'source ./openstack_rc.sh ; openstack keypair delete jenkins ; openstack keypair create jenkins | tee -a id_rsa_jenkins'
            sh("chmod 600 id_rsa_jenkins")
        }

        stage('setup HEAT environment') {
            sh('''
                source ./openstack_rc.sh
                echo "parameter_defaults:"                             > environment.yaml
                echo "  key_name: jenkins"                            >> environment.yaml
                echo "  domain_suffix: \$DOMAIN_SUFFIX"               >> environment.yaml
                echo "  local_domain_suffix: \$LOCAL_DOMAIN_SUFFIX"   >> environment.yaml
                echo "  openshift_openstack_username: \$OS_USERNAME"  >> environment.yaml
                echo "  s3_region_endpoint: \$S3_REGION_ENDPOINT"     >> environment.yaml
                echo "  s3_access_key: \$S3_ACCESS_KEY"               >> environment.yaml
                echo "  s3_secret_key: \$S3_SECRET_KEY"               >> environment.yaml
                echo "  s3_bucket_name: \$S3_BUCKET_NAME"             >> environment.yaml
                echo "  setupMonitoring: true"                        >> environment.yaml
                echo "  controlplane_floating_ip: \$CONTROL_PLANE_IP" >> environment.yaml
                echo "  dataplane_floating_ip: \$DATA_PLANE_IP"       >> environment.yaml
                echo "  do_upgrades: true"                            >> environment.yaml
                echo "  worker_small_scale: \$WORKER_SMALL_SCALE"     >> environment.yaml
                echo "  worker_medium_scale: \$WORKER_MEDIUM_SCALE"   >> environment.yaml
                echo "  worker_large_scale: \$WORKER_LARGE_SCALE"     >> environment.yaml
                echo "  openshift_version: \$OCP_VERSION"             >> environment.yaml
                echo "  set_node_routes: \$SET_NODE_ROUTES"           >> environment.yaml
                echo "  node_routes: \$NODE_ROUTES"                   >> environment.yaml
                echo "  multinetwork: \$MULTINETWORK"                 >> environment.yaml
                echo "  net2_dns_server: \$NET2_DNS_SERVER"           >> environment.yaml
                echo "  net2_external_network: \$NET2_NETWORK"        >> environment.yaml
                echo "  net2_gateway_internal_ip: \$NET2_GATEWAY_IP"  >> environment.yaml
                echo "  net2_ntp_servers: \$NET2_NTP_SERVER"          >> environment.yaml
                echo "  net2_worker_large_scale: \$NET2_LARGE_NODE"   >> environment.yaml
                echo "  net2_worker_medium_scale: \$NET2_MEDIUM_NODE" >> environment.yaml
                echo "  net2_worker_small_scale: \$NET2_SMALL_NODE"   >> environment.yaml
                echo "  net2_node_routes:"                            >> environment.yaml
                echo "    - gateway: "10.2.1.254""                    >> environment.yaml
                echo "      route: "51.179.210.114/32""               >> environment.yaml
                echo "    - gateway: "10.2.1.254""                    >> environment.yaml
                echo "      route: "51.179.217.10/32""                >> environment.yaml
                echo "    - gateway: "10.2.1.254""                    >> environment.yaml
                echo "      route: "51.179.221.162/32""               >> environment.yaml
                echo "  net2_routes:"                                 >> environment.yaml
                echo "    - gateway: "10.2.1.254""                    >> environment.yaml
                echo "      route: "51.179.219.220/32""               >> environment.yaml                        
                echo "  deploy_extra_gateway: \$DEPLOYEXTRAGATEWAY"   >> environment.yaml
                echo "  ansible_branch: v3.11"                        >> environment.yaml
                echo "  slack_webhook_url_acme_sh: \$SLACK_WEBHOOK"   >> environment.yaml
                echo "  neustar_ultradns_username: "openshift""       >> environment.yaml
                echo "  neustar_ultradns_password: \$NEUSTAR_PASSWORD"  >> environment.yaml
                echo "  registry_details:"                            >> environment.yaml 
                echo "    registry_url: \$REG_URL"                      >> environment.yaml
                echo "    registry_user: \$REG_USER"                    >> environment.yaml
                echo "    registry_password: \$REG_PASSWORD"            >> environment.yaml
                echo "  network_config:"                                                  >> environment.yaml
                echo "    allocation_pool: [{"start": "10.2.1.2", "end": "10.2.1.100"}]"  >> environment.yaml
                echo "    cidr: "10.2.1.0/24""                                            >> environment.yaml
                echo "    dns: [ "1.1.1.1" ]"                                             >> environment.yaml
                echo "    gateway: "10.2.1.254""                                          >> environment.yaml
                echo "    bastion_ip: "10.2.1.101""                                       >> environment.yaml
                echo "    service_subnet: "10.2.1.240/29""                                >> environment.yaml
                echo "\$DEPLOY_KEY"                                    >> deploy.pem
            ''')
            sh('cat environment.yaml')
            sh('cat rhel_reg_creds.yaml')
            sh("source ./openstack_rc.sh ; ./deploy.sh \$OS_PASSWORD")
        }

        stage('Set variables HEAT deployment') {
            sh("""
                source ./openstack_rc.sh;
                openstack stack output show openshift-\$OS_PROJECT_NAME bastion_ip -f value -c output_value > env.vars
            """)
        }

        def bastionip = readFile("env.vars").trim()

        stage('Test HEAT deployment') {
            sh("echo BASTION IP = ${bastionip}")
            sh("ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip 'uname -a'")
        }

        stage('checkout openshift deployment code') {
            /*
               openshift-tooling is a private repo, we scp the deploy key
               and pull the code here
            */
            sh("scp -o StrictHostKeyChecking=no -i id_rsa_jenkins deploy.pem cloud-user@$bastionip:")
            sh("ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip 'chmod 600 deploy.pem'")            
            sh("scp -o StrictHostKeyChecking=no -i id_rsa_jenkins id_rsa_jenkins cloud-user@$bastionip:")
            sh("ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip 'chmod 600 id_rsa_jenkins'")
            sh("ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip 'cd /usr/share/ansible/openshift-deployment-ansible ; git branch ; git checkout $openshiftDeploymentAnsibleBranch'; git branch")
        }

        stage('deploy openshift') {
            sh("""
                source ./openstack_rc.sh;
                eval $(ssh-agent -s);
                ssh-add deploy.pem;
                cd /home/cloud-user;
                git clone git@github.com:UKCloud/openshift-tooling.git;
                ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip "cd /usr/share/ansible/openshift-deployment-ansible ; ./deploy-openshift.sh \"\$ADMIN_USERNAME\" \"\$ADMIN_PASSWORD\" \"\$OPENSHIFT_USERNAME\" \"\$OPENSHIFT_PASSWORD\""
            """)
        }

        /*
            The environment variables set by the pipeline need to be overwritten.
            The kubernetes parts of the pipeline automatically override the target
            host, so therefore need to unset them so you can deploy pods within
            the correct environment.
        */
        stage('validate openshift deployment') {
            sh("""
                source ./openstack_rc.sh;
                git clone -b $openshiftDeploymentAnsibleBranch \
                    https://github.com/UKCloud/openshift-deployment-ansible.git openshift-deployment-ansible

                for var in \$(env | grep KUB | cut -d= -f1); do
                    unset \$var;
                done;

                ansible-playbook ./openshift-deployment-ansible/tests/all.yml \
                    --extra-vars OPENSHIFT_USERNAME=\"\$OPENSHIFT_USERNAME\" \
                    --extra-vars OPENSHIFT_PASSWORD=\"\$OPENSHIFT_PASSWORD\" \
                    --extra-vars server=\"https://ocp.\$DOMAIN_SUFFIX:8443\"
    	    ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip \
    	    "/usr/share/ansible/openshift-deployment-ansible/tests/haproxy/master-failover-test.sh \"\$ADMIN_USERNAME\" \"\$ADMIN_PASSWORD\""
            """)
        }

        /*
            Test user creation works (using a randomly-generated password)
        */
        stage('validate openshift user creation') {
            sh("""
                source ./openstack_rc.sh;
                RANDOM_PASSWORD=\$(openssl rand -base64 20 | cut -d= -f1);

                ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip \
                    "cd /usr/share/ansible/openshift-deployment-ansible/tools/ ; ./create-user.sh testUser \$RANDOM_PASSWORD"

                ssh -o StrictHostKeyChecking=no -i id_rsa_jenkins cloud-user@$bastionip \
                    "oc login https://ocp.\$DOMAIN_SUFFIX:8443 --insecure-skip-tls-verify=true -u testUser -p \$RANDOM_PASSWORD"
            """)
        }

        //slackSend color: 'good', message: "Pipeline build Completed Successfully: ${env.JOB_NAME} ${env.BUILD_NUMBER}"


       stage('Cleanup HEAT deployment on successful deployment') {
            sh("""
                source ./openstack_rc.sh;
                openstack stack delete openshift-\$OS_PROJECT_NAME --wait --yes
            """)
        }

    } catch (e) {
        // If there was an exception thrown, the build failed
        //slackSend color: '#c2001f', message: "Pipeline failed :("
        throw e
    } finally {
        // Success or failure, always send notifications
        // slackSend color: '#7ea8c8', message: "Pipeline finished"
    }
}
