apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-build
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: openstack-config
  data:
    openstack_url: ${OPENSTACK_AUTH_URL}
    openstack_project_id: ${OPENSTACK_PROJECT_ID}
    openstack_project_name: ${OPENSTACK_PROJECT_NAME}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    output: {}
    postCommit: {}
    resources: {}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy: {}
      type: JenkinsPipeline
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
parameters:
- description: The OpenStack auth URL of the target environment.
  displayName: OpenStack auth URL
  name: OPENSTACK_AUTH_URL
  required: true
  value: https://cor00005.cna.ukcloud.com/v3
- description: The OpenStack project ID of target environment.
  displayName: OpenStack project ID
  name: OPENSTACK_PROJECT_ID
  required: true
- description: The OpenStack project name  of target environment.
  displayName: OpenStack project name
  name: OPENSTACK_PROJECT_NAME
  required: true
- description: The name assigned to the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: openshift-build 
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/UKCloud/openshift-deployment-jenkins-pipeline.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: jenkins-pipelines/openshift
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
